# Introduction to the shell {#shell}

This is a very brief introduction to some of the most commonly used shell commands.  
A shell is a command line interface allowing access to an operating system's services. Multiple different shells exist, the most popular is probably **bash** (default in most Linux installations), which **zsh** was recently made the default in MacOS (was bash previously). The commands listed here will work similarly in all/most shells.

## Common shell commands
The first thing to look for in a new environment is the help system. In the shell, this is accessed with `man`:
* `man`: Print the manual pages
```{bash eval = FALSE}
man man
```

* `pwd`: Print working directory (the directory you are currently in)
```{bash eval = FALSE}
pwd
```
* `cd`: Set working directory to `/path/to/dir`
```{bash eval = FALSE}
cd /path/to/dir
```
* `mv`: Move `file` from `/current/dir/` to `/new/dir`  
```{bash eval = FALSE}
mv /current/dir/file /new/dir
```
* `mv`: Rename `file` to `newfilename` 
```{bash eval = FALSE}
mv /current/dir/file /current/dir/newfilename
```
* `cp`: Make a copy of `file` from `currentPath` into `altPath`
```{bash eval = FALSE}
cp /currentPath/file /altPath/file
```

* `mkdir`: Create a new directory named 'newdir'
```{bash eval = FALSE}
mkdir /path/to/newdir
```
* `rmdir`: Remove (i.e. delete) `uselessFile`
```{bash eval = FALSE}

```
* `rm`: Remove (i.e. delete) `uselessFile`
```{bash eval = FALSE}
rm /path/to/uselessFile
```
* `cat`: Print contents of `file` to the console
```{bash eval = FALSE}
cat /path/to/file
```
* `uname`: Get system information
```{bash eval = FALSE}
uname -a
```

* `whoami`: When you forget the basics
```{bash eval = FALSE}
whoami
```

## Running system commands within R
You can execute any system command within R using the `system()` command:
```{r}
system("uname -a")
```
