# Resources {#resources}

## R Project

[The R Manuals](https://cran.r-project.org/manuals.html) include a number of resources, including:

* [Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html)
* [CRAN task views](https://cran.r-project.org/web/views/) offer curated lists of packages by topic

## R markdown

* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, J. J. Allaire, Garrett Grolemund
* [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/): how to make websites like this one you are on right now

## Documentation

* [Documentation with roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)

## R for data science

* [R Programming for Data Science](https://leanpub.com/rprogramming) by Roger D. Peng, based mostly on base R, and also covers the basics of [dplyr](https://dplyr.tidyverse.org)
* [R for Data Science](https://r4ds.had.co.nz) by Hadley Wickham & Garrett Grolemund, based on the [tidyverse](https://www.tidyverse.org)
* [Data wrangling, exploration, and analysis with R](https://stat545.com/)

## Graphics

### Plotly

* [Plotly R API](https://plot.ly/r/)
* [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com)

### ggplot2

* [ggplot2](https://ggplot2.tidyverse.org/)

## Advanced R

* [Efficient R Programming](https://bookdown.org/csgillespie/efficientR/) by Colin Gillespie & Robin Lovelace
* [High performance functions with Rcpp](http://adv-r.had.co.nz/Rcpp.html)

## Git and GitHub

* [GitHub guides](https://guides.github.com/)
* [Pro Git Book](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub

## Machine Learning

* [An Introduction to Statistical Learning](https://www-bcf.usc.edu/~gareth/ISL/) offers an accessible view of core learning algorithms, without being math-heavy.
* [Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/) offers a deeper and more extensive view on learning algorithms.
* [Machine Learning with rtemis](https://rtemis.lambdamd.org/)
