{
  "text-color": "#E0E0E0",
  "background-color": "#303030",
  "line-number-color": "#6E6E6E",
  "line-number-background-color": "#303030",
  "text-styles": {
    "Normal": {
      "text-color": "#E0E0E0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#A3A4F8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#79A2CE",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#E0E0E0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#A3A4F8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#ADADAD",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#79A2CE",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#79A2CE",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#A3A4F8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Attribute": {
      "text-color": "#DB9557",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#B3CFE8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#E397EA",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#E397EA",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#E397EA",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#E397EA",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#6CA3A0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#E397EA",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#6CA3A0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#6CA3A0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#6CA3A0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#A3A4F8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#9B9B9B",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Documentation": {
      "text-color": "#9B9B9B",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Annotation": {
      "text-color": "#9B9B9B",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#DB9557",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#9B9B9B",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Information": {
      "text-color": "#9B9B9B",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Warning": {
      "text-color": "#DB9557",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Alert": {
      "text-color": "#F07778",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#F07778",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#ADADAD",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    }
  }
}
