{
  "text-color": "#292929",
  "background-color": "#F7F7F7",
  "line-number-color": "#808080",
  "line-number-background-color": "#F7F7F7",
  "text-styles": {
    "Normal": {
      "text-color": "#292929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#5B58A5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#345B82",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#292929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#5B58A5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#555555",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#345B82",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#345B82",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#5B58A5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Attribute": {
      "text-color": "#955301",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#4D667C",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#8F3799",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#8F3799",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#8F3799",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#8F3799",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#346B69",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#8F3799",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#346B69",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#346B69",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#346B69",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#5B58A5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#626262",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Documentation": {
      "text-color": "#626262",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Annotation": {
      "text-color": "#626262",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#955301",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#626262",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Information": {
      "text-color": "#626262",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Warning": {
      "text-color": "#955301",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Alert": {
      "text-color": "#AB383F",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#AB383F",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#555555",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    }
  }
}
