# Data Table

The [**data.table**](https://github.com/Rdatatable/data.table) package provides 
a modern and highly optimized version of R's data.frame structure. It is highly 
memory efficient and can automatically parallelize internal operations to 
achieve substantial speed improvements over data.frames. The **data.table** 
package weighs in at just a few kilobytes, has zero dependencies, and maintains 
compatibility with R going back many versions.
<br><br>
The twoAdvantages of **data.table** include:

- Super fast reading, writing, and handling of big datasets
    - fast read & write of delimited files with `fread()` and `fwrite()`
    - in-place operations without creating unnecessary copies of data
- Compact and flexible syntax for data manipulation great for handling small or big data

In health data science, it is common to handle very large datasets, especially 
when working with electronic health record 
([EHR](https://en.wikipedia.org/wiki/Electronic_health_record){target="_blank"}) 
data. In such cases, we often have to read, clean, reshape, transform, and merge
multiple tables of different dimensions, often featuring many millions of rows
and thousands of columns. The benefits of `data.table` become immediately 
apparent in such scenarios.
