# Quarto

[Quarto](https://quarto.org/){target="_blank"} is "an open-source scientific and 
technical publishing system built on 
[Pandoc](https://pandoc.org/){target="_blank"}".

It is the evolution of 
[Rmarkdown](https://rmarkdown.rstudio.com/){target="_blank"}, itself built as 
an extension of [Markdown](https://www.markdownguide.org/){target="_blank"}.
<br><br>

[Markdown](https://en.wikipedia.org/wiki/Markdown){target="_blank"}, whose name 
is a play on 
[markup languages](https://en.wikipedia.org/wiki/Markup_language){target="_blank"}, 
is a lightweight, markup language meant to be easily human-readable and can
produce output in multiple formats, like HTML, PDF and many more.
<br><br>

[Rmarkdown](https://rmarkdown.rstudio.com/){target="_blank"} added the ability 
to include executable blocks of R code, which would compile to a Markdown 
document including both the source code and its output, whether that is console 
text output, plots, or other elements, e.g. interactive html objects/widgets. 
This makes it easy to create data-driven reports and presentations within a 
single document. Output formats include PDF, HTML, Word, ePub, and more.
<br><br>

Quarto brings the same functionality to more languages, including 
[R](https://www.r-project.org/){target="_blank"}, 
[Python](https://www.python.org/){target="_blank"},
[Julia](https://julialang.org/){target="_blank"}, and 
[Observable JS](https://observablehq.com/){target="_blank"}.

## IDEs

**RStudio** and **VS Code** both feature support for authoring and rendering/previewing
Quarto documents. **RStudio** includes built-in support for Quarto and may ask you to 
install additional packages when rendering a Quarto document for the first time.
**VS Code** requires the installation of the 
[Quarto extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto).
<br><br>

This online book/website has been written in Quarto.

## Resources

Learn more about Quarto and access its full documentation on the official 
website: [https://quarto.org/](https://quarto.org/){target="_blank"}.
