# Reproducibility, Robustness, Replicability {#sec-reprobrep}

**Reproducibility**, **robustness**, and **replicability**, are essential concepts
in science and data science. A short definition of each can help understand and 
remember the differences between them:

## Definitions

- **Reproducibility**: ability to produce consistent results given the same dataset and same analysis
- **Robustness**: ability to produce the consistent results given same dataset and different analysis
- **Replicability**: ability to produce the consistent results given different dataset and different analysis

## Why it matters

To some extent this is obvious, but it is worth considering acquisition of knowledge

- In basic science: 
  - Hypotheses and interpretation of results are often based on existing knowledge and theories
  - Replicability & reproducibility are important for making progress in scientific research & acquisition of new knowledge
- In applied science, clinical medicine:
  - Evidence-based medicine, trust, effectiveness

## Some bad examples

- https://www.science.org/content/article/research-misconduct-finding-neuroscientist-eliezer-masliah-papers-under-suspicion

## Resources

- [@nosek2022replicability]
