# Resources {#sec-resources}

## R Project

[The R Manuals](https://cran.r-project.org/manuals.html){target="_blank"} include a number of resources, including:

- [Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html){target="_blank"}
- [CRAN task views](https://cran.r-project.org/web/views/){target="_blank"} offer curated lists of packages by topic

## R programming

- [Advanced R](https://adv-r.hadley.nz/){target="_blank"} by Hadley Wickham
- [Efficient R Programming](https://bookdown.org/csgillespie/efficientR/){target="_blank"} by Colin Gillespie & Robin Lovelace
- [Rcpp: Seamless R and C++ Integration](https://www.rcpp.org/){target="_blank"}
- [Parallel and Distributed Processing with future](https://future.futureverse.org/){target="_blank"}

## R for data science

- [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/){target="_blank"} by Roger D. Peng, based mostly on base R, and also covers the basics of **dplyr**.
- [Data wrangling, exploration, and analysis with R b y Jenny Bryan](https://stat545.com/)
- [R for Data Science](https://r4ds.had.co.nz/){target="_blank"} by Hadley Wickham & Garrett Grolemund

## Markdown

- [Original guide by the author of Markdown](https://daringfireball.net/projects/markdown/){target="_blank"}
- [Markdown guide by Matt Cone](https://www.markdownguide.org/){target="_blank"}

## R markdown

Note: Quarto has superseded R Markdown as the recommended tool for authoring documents in R.

- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/){target="_blank"} by Yihui Xie, J. J. Allaire, Garrett Grolemund
- [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/){target="_blank"}: how to make websites like this one you are on right now

## Quarto

- [Quarto home](https://quarto.org/){target="_blank"}

## Writing R Documentation

- [Documentation with roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html){target="_blank"}

## Graphics

### ggplot2

- [ggplot2](https://ggplot2.tidyverse.org/){target="_blank"}

### Plotly

- [Plotly R API](https://plot.ly/r/){target="_blank"}
- [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com){target="_blank"}

## Git and GitHub

- [GitHub guides](https://guides.github.com/)
- [Pro Git Book](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub

## Machine Learning

- [An Introduction to Statistical Learning](https://www-bcf.usc.edu/~gareth/ISL/) offers an accessible view of core learning algorithms, without being math-heavy.
- [Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/) offers a deeper and more extensive view on learning algorithms.
- [Machine Learning with rtemis](https://rtemis.lambdamd.org/)

## Datasets

A number of online repositories offer free access to datasets suitable for 
data science / statistics / machine learning. Some of them are:
<br><br>

- [Kaggle Datasets](https://www.kaggle.com/datasets)
- [NIH Data Repositories](https://www.nlm.nih.gov/NIHbmic/nih_data_sharing_repositories.html)
- [OpenML](https://www.openml.org)
- [Penn ML Benchmarks](https://github.com/EpistasisLab/penn-ml-benchmarks)
- [PLOS Recommended Repositories](https://journals.plos.org/plosone/s/recommended-repositories)
- [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php)
- [UCSF Library Resources](https://guides.ucsf.edu/datamgmt/repository)
- [Wikipedia's List of datasets for machine-learning research](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)
